skins:
  - lightgray

toolbar:
  - styleselect | bold italic | undo redo
  - image | link
plugins:
  - image
  - link
  - code
  - fullpage
  - imagetools
  - textcolor
  - textpattern
  - template
  - pagebreak
  - save
  - spellchecker
  - visualblocks
  - preview
  - importcss
  - visualchars
  - media

  branding: false