

theme: "modern"
skins: "lightgray"

schema: "html5-strict"
element_format: "html"
resize: true

toolbar:
  - cut copy paste pastetext pasteword | search replace | undo redo | link unlink anchor image cleanup help code | insertdate inserttime preview
  - bold italic underline strikethrough | justifyleft justifycenter justifyright justifyfull | sub sup | bullist numlist | outdent indent blockquote"
  - styleselect formatselect fontselect fontsizeselect | forecolor backcolor
  - tablecontrols | hr removeformat visualaid
  - fullscreen | charmap media | visualchars blockquote
plugins:
  - image
  - code
  - contextmenu
  - link
  - code
  - fullpage
  - imagetools
  - textcolor
  - textpattern
  - template
  - pagebreak
  - save
  - spellchecker
  - visualblocks
  - preview
  - importcss
  - visualchars
  - media
  - textpattern
  - table
  - insertdatetime
  - preview
  - media
  - searchreplace
  - contextmenu
  - paste
  - directionality
  - fullscreen
  - noneditable
  - visualchars
  - nonbreaking
  - template

branding: false