

theme: "modern"
skins: "lightgray"

schema: "html5-strict"
element_format: "html"
resize: true

menubar: false
paste_merge_formats: true
paste_retain_style_properties: all

toolbar:
  - formatselect | fontselect | fontsizeselect | bold | italic | underline | strikethrough | alignleft | aligncenter | alignjustify | alignright
  - bullist | numlist | outdent | indent | blockquote | forecolor | backcolor | undo | redo | link | unlink | preview | hr | searchreplace
  - cut copy paste pastetext pasteword | search replace | undo redo | link unlink anchor image cleanup help code | insertdate inserttime preview
  - bold italic underline strikethrough | justifyleft justifycenter justifyright justifyfull | sub sup | bullist numlist | outdent indent blockquote"
  
plugins:
  - wordcount
  - image
  - code
  - contextmenu
  - link
  - code
  - fullpage
  - imagetools
  - textcolor
  - textpattern
  - template
  - pagebreak
  - save
  - spellchecker
  - visualblocks
  - importcss
  - visualchars
  - media
  - textpattern
  - table
  - insertdatetime
  - media
  - searchreplace
  - contextmenu
  - paste
  - directionality
  - fullscreen
  - noneditable
  - visualchars
  - nonbreaking
  - template

branding: false